services:
  rust-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rust_app
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/gatekeeper
      REDIS_URL: redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    ports:
      - "8080:8080"