name: Rust Build and Test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install dependencies
        run: cargo fetch

      - name: Run tests
        run: cargo test --verbose

      - name: Build project
        run: cargo build --release

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: rust-app-build
          path: target/release/
